### ISSUE TITLE
Clarify GPLv3 license use

### ISSUE THREAD

**Issue by scottmessinger** [SortableJS/ember-sortablejs#21]
Hi!

This project looks great, but I have a question about the license. It looks like it's a GPL v3 license. To my understanding, that means if I use this library in my web app, I have to open source my entire web app under GPL v3:

> Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, **which include larger works using a licensed work,** under the same license. [1]

Is my understanding correct? 

[1] https://github.com/SortableJS/ember-sortablejs/blob/master/LICENSE.md

**Comment by scottmessinger** [comment]
Hi! I'd love to follow up on this! Am I understanding the license you're using correctly?

**Comment by lvegerano** [comment]
I'll take a look at it later today. But 
> if I use this library in my web app, I have to open source my entire web app

Is not my intention
