### ISSUE TITLE
Disabled option doesn't work correctly. 

### ISSUE THREAD

**Issue by arthay** [SortableJS/ember-sortablejs#9]
In our case when the disabled option is a dynamic value, the option works correctly the first time but after changing the value to false, the first level of nested sortable works incorrectly.

`<SortableJs
    class="sortable"
    @options={{hash animation=150 fallbackOnBody=true swapThreshold=0.65 group=group dragClass="sortable-drag" disabled=disabledSortable }}
    @onEnd={{action onEnd}}
    @onChoose={{action "onChoose"}}
    @onUnchoose={{action onUnchoose}}
    @onChange={{action "onChange"}}
>

    <div class="tree-sortable>
        {{#if sortedTreeData.length}}
            {{#each sortedTreeData as |treeItem|}}
                <TreeItem
                    @treeItem={{treeItem}}
                    @onEnd={{action onEnd}}
                    @onChoose={{action onChoose}}
                    @onUnchoose={{action onUnchoose}} />
            {{/each}}
        {{/if}}
    </div>

</SortableJs>`

**Comment by lvegerano** [comment]
I will take a look at this today. Thanks for reporting!

**Comment by arthay** [comment]
Thanks for a quick response.
